# Generated by Django 2.2.7 on 2019-11-26 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_deadline', models.DateTimeField(blank=True, null=True)),
                ('permutation_number_deadline', models.DateTimeField(blank=True, null=True)),
                ('credentials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.BinaryField(blank=True, max_length=64, null=True, unique=True)),
                ('permutation_commitment', models.BinaryField(blank=True, max_length=32, null=True)),
                ('permutation_number', models.BinaryField(blank=True, max_length=32, null=True)),
                ('recipient_cipher', models.CharField(max_length=64)),
                ('recipient_plaintext', models.CharField(max_length=64)),
                ('gifter_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter', to='allotment.Participant')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.Party')),
                ('recipient_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='allotment.Participant')),
            ],
        ),
    ]
