# Generated by Django 2.2.7 on 2019-12-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='recipient_cipher',
            field=models.CharField(max_length=4096),
        ),
    ]
